version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.4

    working_directory: ~/frontend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-11-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-11-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-11-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn lint
      
      - store_test_results:  # upload junit test results for display in Test Summary
          # Read more: https://circleci.com/docs/2.0/collect-test-data/
          path: _build/test/lib/frontend # Replace with the name of your :app