version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-11-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-11-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-11-dependencies-{{ checksum "package.json" }}

      # run tests!
- run: yarn lint